export enum MonthlyReadingActionTypes {
  GET_MONTHLY_READING = "GET_MONTHLY_READING",
  GET_MONTHLY_READING_SUCCEEDED="GET_MONTHLY_READING_SUCCEEDED",
  GET_MONTHLY_READING_FAILED="GET_MONTHLY_READING_FAILED",
  FILTER_SENSOR_LOGS = "FILTER_SENSOR_LOGS",
  FILTER_SENSOR_LOGS_SUCCEEDED="FILTER_SENSOR_LOGS_SUCCEEDED",
  FILTER_SENSOR_LOGS_FAILED="FILTER_SENSOR_LOGS_FAILED",
}

